
# DyrosDynamicWalkPPO.yaml - 기존 설정 기반 간략화
_defaults:
  - _self_
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default
  - vecenv: isaacgym
  - task: DyrosDynamicWalk
  - algo: a2c_continuous
  - model: continuous_a2c_logstd_dyros
  - reward_shaper: default_rewards

hydra:
  run:
    dir: ./runs/${task.name}
  output_subdir: null

runner:
  save_interval: 100
  save_dir: runs/${task.name}/nn

params:
  seed: ${...seed}

  algo:
    name: a2c_continuous
    gamma: 0.995 

  reward_shaper:
    scale_value: 1.0

  model:
    name: continuous_a2c_logstd_dyros
    rnn_hidden: 256
    latent_dim: 32               # ← 32차원으로 수정
    reg_loss_coef: 0.002         # ← DWL 논문값으로 수정

  network:
    name: dyros_actor_critic
    separate: False
    params:
      input_shape: [126]         # ← 126차원으로 수정
      priv_dim: 144             # ← 144차원으로 수정  
      actions_num: 13
      z_dim: 32                 # ← 32차원으로 수정
      
    rnn:
      name: gru
      units: 256
      layers: 1
      before_mlp: false         # ← 기존값 유지
      concat_input: true        # ← 기존값 유지

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -2.302585          # ← 기존값 유지 (ln(1/10))
        sigma_last:
          name: const_initializer
          val: -2.9957            # ← 기존값 유지 (ln(1/20))
        fixed_sigma: False        # ← 기존값 유지 (learnable)

      initializer:
        name: orthogonal_initializer
        gain: 0.01
      regularizer:
        name: None

    mlp:
      units: [512, 512, 256]
      activation: relu
      d2rl: False
      input_num: 144              # ← 144로 수정 (privileged state)

      initializer:
        name: orthogonal_initializer
        gain: 0.01

  load_checkpoint: ${if:${...checkpoint},True,False}
  load_path: ${...checkpoint}

  env_name: rlgpu

  config:
    name: ${resolve_default:DyrosDynamicWalk,${....experiment}}
    full_experiment_name: ${.name}
    multi_gpu: False
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    clip_actions: True
    num_actors: ${....task.env.numEnvs}
    
    reward_shaper:
      scale_value: 1.0
      
    normalize_advantage: True 
    gamma: 0.995
    tau: 0.95
    learning_rate: 1e-5           # ← 기존값 유지
    learning_rate_min: 5e-6
    lr_schedule: linear
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:20000,${....max_iterations}}
    save_best_after: 200
    save_frequency: 100
    print_stats: True
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    ppo: True
    use_estimator_network: False
    e_clip: 0.3
    
    # 중요한 하이퍼파라미터들 (기존값 유지)
    horizon_length: 128           # ← 기존값 유지
    minibatch_size: 4096          # ← 기존값 유지  
    mini_epochs: 3                # ← 기존값 유지
    seq_len: 4                    # ← 기존값 유지
    
    critic_coef: 5                # ← value_coef
    policy_coef: 5                # ← DWL policy weight
    clip_value: True
    bounds_loss_coef: 0.
    reg_loss_coef: 0.002          # ← DWL regularization (수정)
    
    # Logging
    wandb_activate: True
    log_wandb_frequency: 10
    num_rewards: 14
    num_extra_logging: 12
    separate_opt: True